// Visual QA gallery builder — see README.md in this directory.
// Run: node tests/visual-qa/gallery.js (after capture.js)
const fs = require('fs');
const path = require('path');

const OUT_DIR = path.resolve(__dirname, 'output');
const GALLERY_PATH = path.join(OUT_DIR, 'gallery.html');

// Order groups appear in the gallery — anything in the manifest but not
// listed here falls back to appearing after these, in first-seen order.
const GROUP_ORDER = [
	'Page types',
	'Extension states',
	'Viewport widths',
	'Native Tools menu',
	'Locales',
	'Dark mode',
];

function humanizeName(filename) {
	return filename
		.replace(/\.png$/, '')
		.replace(/^\d+[a-z]?-/, '')
		.replace(/-/g, ' ');
}

function build() {
	if (!fs.existsSync(OUT_DIR)) {
		console.error(`No output directory at ${OUT_DIR} — run capture.js first.`);
		process.exit(1);
	}
	const files = fs.readdirSync(OUT_DIR).filter((f) => f.endsWith('.png'));
	if (files.length === 0) {
		console.error('No screenshots found — run capture.js first.');
		process.exit(1);
	}

	const manifestPath = path.join(OUT_DIR, 'manifest.json');
	const manifest = fs.existsSync(manifestPath)
		? JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
		: [];
	const groupByFile = new Map(manifest.map((m) => [`${m.name}.png`, m.group]));

	const byGroup = {};
	const order = [...GROUP_ORDER];
	for (const file of files.sort()) {
		const group = groupByFile.get(file) || 'Other';
		if (!order.includes(group)) order.push(group);
		(byGroup[group] = byGroup[group] || []).push(file);
	}

	const sections = order.filter((g) => byGroup[g]?.length)
		.map((group) => {
			const figures = byGroup[group]
				.map((file) => {
					const b64 = fs.readFileSync(path.join(OUT_DIR, file)).toString('base64');
					return `<figure>
	<img src="data:image/png;base64,${b64}" alt="${humanizeName(file)}" loading="lazy" />
	<figcaption>${humanizeName(file)}</figcaption>
</figure>`;
				})
				.join('\n');
			return `<section>
	<h2>${group}</h2>
	<div class="grid">
${figures}
	</div>
</section>`;
		})
		.join('\n');

	const html = `<title>Google Search by Date — Visual QA Gallery</title>
<style>
  :root {
    --bg: #f6f5f2; --panel: #ffffff; --ink: #201f1c; --muted: #6b6862;
    --line: #e4e1da; --accent: #3a5ba0;
  }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #1b1a17; --panel: #242320; --ink: #ece9e2; --muted: #a39d90; --line: #38352f; --accent: #7fa2e0; }
  }
  :root[data-theme="dark"] { --bg: #1b1a17; --panel: #242320; --ink: #ece9e2; --muted: #a39d90; --line: #38352f; --accent: #7fa2e0; }
  :root[data-theme="light"] { --bg: #f6f5f2; --panel: #ffffff; --ink: #201f1c; --muted: #6b6862; --line: #e4e1da; --accent: #3a5ba0; }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--ink); font-family: -apple-system, "Segoe UI", system-ui, sans-serif; padding: 40px 20px 80px; }
  main { max-width: 1400px; margin: 0 auto; }
  h1 { font-size: 22px; font-weight: 650; margin: 0 0 6px; }
  p.lede { color: var(--muted); margin: 0 0 40px; font-size: 14px; max-width: 70ch; }
  section { margin-bottom: 44px; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--accent); font-weight: 650; margin: 0 0 14px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(360px, 1fr)); gap: 18px; }
  figure { margin: 0; background: var(--panel); border: 1px solid var(--line); border-radius: 6px; overflow: hidden; }
  figure img { display: block; width: 100%; height: auto; }
  figcaption { padding: 8px 12px; font-size: 12px; color: var(--muted); border-top: 1px solid var(--line); text-transform: capitalize; }
</style>
<main>
  <h1>Google Search by Date — Visual QA Gallery</h1>
  <p class="lede">Real screenshots from live google.com pages with the extension loaded, across varied page types, extension states, native menu interactions, and locales. Generated by tests/visual-qa/.</p>
${sections}
</main>
`;

	fs.writeFileSync(GALLERY_PATH, html);
	console.log(`Wrote ${GALLERY_PATH} (${files.length} screenshots)`);
}

build();
